# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autotaskUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(679, 516)
        self.btnsubmit = QtWidgets.QPushButton(Dialog)
        self.btnsubmit.setGeometry(QtCore.QRect(360, 470, 113, 32))
        self.btnsubmit.setObjectName("btnsubmit")
        self.btncancle = QtWidgets.QPushButton(Dialog)
        self.btncancle.setGeometry(QtCore.QRect(240, 470, 113, 32))
        self.btncancle.setObjectName("btncancle")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 621, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.chkboxrelogin = QtWidgets.QCheckBox(self.tab)
        self.chkboxrelogin.setGeometry(QtCore.QRect(180, 80, 191, 20))
        self.chkboxrelogin.setObjectName("chkboxrelogin")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 91, 31))
        self.label_3.setObjectName("label_3")
        self.cmbboxTaskType = QtWidgets.QComboBox(self.tab)
        self.cmbboxTaskType.setGeometry(QtCore.QRect(180, 30, 141, 32))
        self.cmbboxTaskType.setObjectName("cmbboxTaskType")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 111, 16))
        self.label_5.setObjectName("label_5")
        self.editHkUserServer = QtWidgets.QLineEdit(self.tab)
        self.editHkUserServer.setGeometry(QtCore.QRect(180, 220, 301, 21))
        self.editHkUserServer.setObjectName("editHkUserServer")
        self.editSmsServer = QtWidgets.QLineEdit(self.tab)
        self.editSmsServer.setGeometry(QtCore.QRect(180, 180, 301, 21))
        self.editSmsServer.setObjectName("editSmsServer")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 151, 16))
        self.label_6.setObjectName("label_6")
        self.editTestUser = QtWidgets.QLineEdit(self.tab)
        self.editTestUser.setGeometry(QtCore.QRect(180, 260, 301, 21))
        self.editTestUser.setObjectName("editTestUser")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(50, 280, 121, 16))
        self.label_7.setObjectName("label_7")
        self.chkboxreinstall = QtWidgets.QCheckBox(self.tab)
        self.chkboxreinstall.setGeometry(QtCore.QRect(180, 310, 181, 20))
        self.chkboxreinstall.setObjectName("chkboxreinstall")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(80, 340, 81, 16))
        self.label_8.setObjectName("label_8")
        self.editappfile = QtWidgets.QLineEdit(self.tab)
        self.editappfile.setGeometry(QtCore.QRect(180, 340, 391, 21))
        self.editappfile.setObjectName("editappfile")
        self.chkboxfight = QtWidgets.QCheckBox(self.tab)
        self.chkboxfight.setGeometry(QtCore.QRect(180, 110, 211, 20))
        self.chkboxfight.setObjectName("chkboxfight")
        self.chkboxrestartmobile = QtWidgets.QCheckBox(self.tab)
        self.chkboxrestartmobile.setGeometry(QtCore.QRect(320, 140, 161, 20))
        self.chkboxrestartmobile.setObjectName("chkboxrestartmobile")
        self.chkboxautodrag = QtWidgets.QCheckBox(self.tab)
        self.chkboxautodrag.setGeometry(QtCore.QRect(180, 140, 121, 20))
        self.chkboxautodrag.setObjectName("chkboxautodrag")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(90, 60, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(89, 100, 91, 20))
        self.label_10.setObjectName("label_10")
        self.lineEdit_login = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_login.setGeometry(QtCore.QRect(210, 60, 113, 21))
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(90, 140, 91, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(90, 180, 91, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(90, 220, 101, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_login_report = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_login_report.setGeometry(QtCore.QRect(210, 90, 113, 21))
        self.lineEdit_login_report.setObjectName("lineEdit_login_report")
        self.lineEdit_reg = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_reg.setGeometry(QtCore.QRect(210, 140, 113, 21))
        self.lineEdit_reg.setObjectName("lineEdit_reg")
        self.lineEdit_reg_report = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_reg_report.setGeometry(QtCore.QRect(210, 180, 113, 21))
        self.lineEdit_reg_report.setObjectName("lineEdit_reg_report")
        self.lineEdit_reg_up_qrcode = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_reg_up_qrcode.setGeometry(QtCore.QRect(210, 220, 113, 21))
        self.lineEdit_reg_up_qrcode.setObjectName("lineEdit_reg_up_qrcode")
        self.lineEdit_reportneedfriend = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_reportneedfriend.setGeometry(QtCore.QRect(210, 260, 113, 21))
        self.lineEdit_reportneedfriend.setObjectName("lineEdit_reportneedfriend")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(90, 260, 101, 16))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnclear = QtWidgets.QPushButton(self.tab_2)
        self.btnclear.setGeometry(QtCore.QRect(500, 240, 91, 32))
        self.btnclear.setObjectName("btnclear")
        self.btnup = QtWidgets.QPushButton(self.tab_2)
        self.btnup.setGeometry(QtCore.QRect(500, 110, 91, 32))
        self.btnup.setObjectName("btnup")
        self.listfull = QtWidgets.QListWidget(self.tab_2)
        self.listfull.setGeometry(QtCore.QRect(30, 90, 211, 231))
        self.listfull.setObjectName("listfull")
        self.listsel = QtWidgets.QListWidget(self.tab_2)
        self.listsel.setGeometry(QtCore.QRect(260, 90, 231, 231))
        self.listsel.setObjectName("listsel")
        self.btndown = QtWidgets.QPushButton(self.tab_2)
        self.btndown.setGeometry(QtCore.QRect(500, 150, 91, 32))
        self.btndown.setObjectName("btndown")
        self.chkboxreimgbak = QtWidgets.QCheckBox(self.tab_2)
        self.chkboxreimgbak.setGeometry(QtCore.QRect(340, 20, 151, 20))
        self.chkboxreimgbak.setObjectName("chkboxreimgbak")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 211, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(260, 60, 241, 16))
        self.label.setObjectName("label")
        self.lbMsg = QtWidgets.QLabel(self.tab_2)
        self.lbMsg.setGeometry(QtCore.QRect(40, 330, 531, 31))
        self.lbMsg.setObjectName("lbMsg")
        self.chkboxswg = QtWidgets.QCheckBox(self.tab_2)
        self.chkboxswg.setGeometry(QtCore.QRect(40, 20, 291, 20))
        self.chkboxswg.setObjectName("chkboxswg")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "参数设置"))
        self.btnsubmit.setText(_translate("Dialog", "提交"))
        self.btncancle.setText(_translate("Dialog", "取消"))
        self.chkboxrelogin.setText(_translate("Dialog", "账号每次都必须重新登录"))
        self.label_3.setText(_translate("Dialog", "脚本运行模式"))
        self.label_4.setText(_translate("Dialog", "短信服务器地址"))
        self.label_5.setText(_translate("Dialog", "业务服务器地址"))
        self.label_6.setText(_translate("Dialog", "仅供测试登录的账号"))
        self.label_7.setText(_translate("Dialog", "格式 账号----密码"))
        self.chkboxreinstall.setText(_translate("Dialog", "每次都必须重装目标APP"))
        self.label_8.setText(_translate("Dialog", "目标APP路径"))
        self.chkboxfight.setText(_translate("Dialog", "每次登录前必须先开关飞行模式"))
        self.chkboxrestartmobile.setText(_translate("Dialog", "每次登录必须重启手机"))
        self.chkboxautodrag.setText(_translate("Dialog", "允许自动拖图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "基础设置"))
        self.label_9.setText(_translate("Dialog", "登录获取账号"))
        self.label_10.setText(_translate("Dialog", "登录成功上报"))
        self.label_11.setText(_translate("Dialog", "注册获取账号"))
        self.label_12.setText(_translate("Dialog", "注册成功上报"))
        self.label_13.setText(_translate("Dialog", "注册上传二维码"))
        self.label_14.setText(_translate("Dialog", "通报需要好友"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "数据库"))
        self.btnclear.setText(_translate("Dialog", "清空"))
        self.btnup.setText(_translate("Dialog", "上移"))
        self.btndown.setText(_translate("Dialog", "下移"))
        self.chkboxreimgbak.setText(_translate("Dialog", "一律重做数据备份"))
        self.label_2.setText(_translate("Dialog", "所有可用的任务列表(双击选用项)"))
        self.label.setText(_translate("Dialog", "当前已经选用的任务列表(双击移除项)"))
        self.lbMsg.setText(_translate("Dialog", "..."))
        self.chkboxswg.setText(_translate("Dialog", "开启自动任务（允许登录成功后自动执行）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "自动任务"))

