# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gBoxBtns = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxBtns.setObjectName("gBoxBtns")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gBoxBtns)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 35, 101, 263))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gboxvLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.gboxvLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gboxvLayout.setContentsMargins(0, 0, 0, 0)
        self.gboxvLayout.setObjectName("gboxvLayout")
        self.btnchklinks = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnchklinks.setObjectName("btnchklinks")
        self.gboxvLayout.addWidget(self.btnchklinks)
        self.btnstart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnstart.setObjectName("btnstart")
        self.gboxvLayout.addWidget(self.btnstart)
        self.btnSelAll = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSelAll.setObjectName("btnSelAll")
        self.gboxvLayout.addWidget(self.btnSelAll)
        self.btnRevSelAll = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnRevSelAll.setObjectName("btnRevSelAll")
        self.gboxvLayout.addWidget(self.btnRevSelAll)
        self.btnUnSelAll = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnUnSelAll.setObjectName("btnUnSelAll")
        self.gboxvLayout.addWidget(self.btnUnSelAll)
        self.btnstop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnstop.setObjectName("btnstop")
        self.gboxvLayout.addWidget(self.btnstop)
        self.lbShellType = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbShellType.setObjectName("lbShellType")
        self.gboxvLayout.addWidget(self.lbShellType)
        self.labelver = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelver.setObjectName("labelver")
        self.gboxvLayout.addWidget(self.labelver)
        self.horizontalLayout.addWidget(self.gBoxBtns)
        self.iponeTbWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.iponeTbWidget.setObjectName("iponeTbWidget")
        self.iponeTbWidget.setColumnCount(0)
        self.iponeTbWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.iponeTbWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.txtoutLogs = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtoutLogs.setReadOnly(True)
        self.txtoutLogs.setObjectName("txtoutLogs")
        self.verticalLayout_2.addWidget(self.txtoutLogs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_about = QtWidgets.QMenu(self.menubar)
        self.menu_about.setObjectName("menu_about")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.menu.addAction(self.actionexit)
        self.menu_about.addAction(self.actionabout)
        self.menu_about.addAction(self.actionhelp)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_about.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gBoxBtns.setTitle(_translate("MainWindow", "功能按钮              "))
        self.btnchklinks.setText(_translate("MainWindow", "检测连接"))
        self.btnstart.setText(_translate("MainWindow", "开始"))
        self.btnSelAll.setText(_translate("MainWindow", "全选"))
        self.btnRevSelAll.setText(_translate("MainWindow", "反选"))
        self.btnUnSelAll.setText(_translate("MainWindow", "全部不选"))
        self.btnstop.setText(_translate("MainWindow", "配置任务"))
        self.lbShellType.setText(_translate("MainWindow", "..."))
        self.labelver.setText(_translate("MainWindow", "版本"))
        self.menu.setTitle(_translate("MainWindow", " file"))
        self.menu_about.setTitle(_translate("MainWindow", " about"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionhelp.setText(_translate("MainWindow", "help"))

